export interface ProgrammeDay {
  type: string;
  title?: string;
  core?: string[];
  taskType?: string;
  task?: string[];
  output?: string;
  theme?: string;
  present?: string[];
  criteria?: string[];
  awards?: string[];
}

export interface ProgrammeData {
  icon: string;
  name: string;
  blurb: string;
  progress: number;
  dayLabel: string;
  cert: string;
  days: {
    mon: ProgrammeDay;
    tue: ProgrammeDay;
    wed: ProgrammeDay;
    thu: ProgrammeDay;
    fri: ProgrammeDay;
    sat: ProgrammeDay;
  };
}

export const programmeData: Record<string, ProgrammeData> = {
  estate: {
    icon: "building",
    name: "Estate Management",
    blurb: "Property administration, valuation, and the business of real estate in Nigeria.",
    progress: 80,
    dayLabel: "Day 5 of 6",
    cert: "Professional Certificate in Estate Management",
    days: {
      mon: { type: "Individual Class · Activity Day", title: "Foundations of Estate Management & Property Administration",
        core: ["Introduction to Estate Management", "Roles and Responsibilities of an Estate Manager", "Overview of the Nigerian Real Estate Industry", "Types of Properties (Residential, Commercial, Industrial, Agricultural, Mixed-Use)", "Land Ownership Systems in Nigeria", "Property Rights and the Land Use Act", "Basic Real Estate Terminologies", "Ethics and Professional Conduct", "Career Opportunities in Estate Management", "Importance of Estate Management in Community Development"],
        taskType: "Individual Task", task: ['Write: "What Estate Management Means to Me."', "Identify five property types within your community", "List three property-related challenges in your locality", "Identify one undeveloped property with potential"],
        output: "Personal Estate Management Reflection Sheet" },
      tue: { type: "Group Class · Collaboration Day", title: "Property Identification, Documentation & Market Analysis",
        core: ["Identifying Real Estate Opportunities", "Property Inspection Techniques", "Understanding Property Documentation", "Introduction to Property Valuation", "Factors Affecting Property Value", "Community Property Mapping", "Housing Needs Assessment", "Real Estate Market Analysis", "Identifying Investment Opportunities", "Risk Assessment in Property Acquisition"],
        taskType: "Group Task", task: ["Survey a selected community (real or simulated)", "Identify one major housing or property challenge", "Analyze available land and property opportunities", "Identify stakeholders", "Define the selected problem clearly"],
        output: "Community Property Assessment Report" },
      wed: { type: "Individual Skill Practice Day", title: "Property Management, Client Relations & Facility Administration",
        core: ["Principles of Property Management", "Tenant and Landlord Relationships", "Rent Administration", "Lease Agreements", "Facility Management", "Property Maintenance Planning", "Client Relationship Management", "Negotiation Skills", "Real Estate Marketing", "Professional Ethics in Property Transactions"],
        taskType: "Individual Task", task: ["Prepare a property management plan for a residential building", 'Write: "How I would manage a residential estate effectively."', "Develop a one-minute property marketing pitch", "List five qualities of a successful estate manager"],
        output: "Individual Property Management Plan" },
      thu: { type: "Group Project Development Day", title: "Real Estate Development, Investment & Project Planning",
        core: ["Real Estate Development Process", "Land Development Planning", "Affordable Housing Concepts", "Cost Estimation Basics", "Project Planning and Scheduling", "Stakeholder Engagement", "Risk Management in Property Development", "Sustainable Estate Development", "Community Infrastructure Planning", "Team Collaboration in Real Estate Projects"],
        taskType: "Group Task", task: ["Develop a practical real estate solution to Tuesday’s challenge", "Assign responsibilities among team members", "Prepare an implementation strategy", "Estimate project requirements and resources"],
        output: "Group Real Estate Development Strategy" },
      fri: { type: "Capstone Project Day", title: "Estate Development Strategy & Community Housing Solutions",
        core: ["Transforming Property Ideas into Practical Projects", "Developing Sustainable Community Housing Solutions", "Property Investment Planning", "Financial Feasibility Basics", "Risk Identification and Mitigation", "Monitoring and Evaluation of Real Estate Projects", "Community Impact Assessment", "Preparing Professional Project Presentations"],
        taskType: "Capstone · Group Task", task: ["Problem Definition", "Estate Development Strategy", "Implementation Plan", "Team Responsibilities", "Expected Outcomes"],
        output: "Final Capstone Project Document" },
      sat: { type: "Graduation", theme: "Presenting Solutions, Celebrating Excellence & Becoming Certified Professionals",
        present: ["Community or property challenge identified", "Background of the problem", "Root cause analysis", "Proposed estate management solution", "Implementation plan", "Expected outcomes and community impact", "Q&A with the assessment panel"],
        criteria: ["Problem Identification and Analysis", "Practicality of the Proposed Solution", "Innovation and Creativity", "Feasibility and Sustainability", "Team Collaboration", "Communication and Presentation Skills", "Professionalism"],
        awards: ["Best Estate Development Project", "Best Property Management Strategy", "Most Innovative Real Estate Solution", "Best Team Collaboration", "Best Project Presentation", "Outstanding Participant"] },
    },
  },
  agro: {
    icon: "tree",
    name: "Agro-Allied",
    blurb: "Turn farming into enterprise: value chains, agro-processing, and market access.",
    progress: 0, dayLabel: "Starts Monday",
    cert: "Professional Certificate in Agro-Allied",
    days: {
      mon: { type: "Individual Class · Activity Day", title: "Introduction to Agriculture & Agro-Allied Development",
        core: ["Introduction to Agriculture and the Agro-Allied Sector", "Importance of Agriculture to Economic Development", "Agricultural Value Chains", "Crop Production Fundamentals", "Livestock Production Systems", "Fish Farming and Aquaculture", "Poultry Farming Opportunities", "Sustainable Agricultural Practices", "Agricultural Entrepreneurship", "Career Opportunities in the Agro-Allied Industry"],
        taskType: "Individual Task", task: ['Write: "What Agriculture Means to My Community."', "Identify five agricultural products in your locality", "List three agricultural challenges affecting your community", "Identify one agricultural opportunity for jobs or food security"],
        output: "Personal Agricultural Reflection Sheet" },
      tue: { type: "Group Class · Collaboration Day", title: "Farm Resource Management & Agricultural Production Planning",
        core: ["Soil Types and Fertility Management", "Land Preparation Techniques", "Crop Selection and Seasonal Farming", "Livestock Housing and Management", "Agricultural Inputs and Farm Equipment", "Irrigation and Water Management", "Pest and Disease Management", "Climate-Smart Agriculture", "Farm Planning Techniques", "Good Agricultural Practices (GAP)"],
        taskType: "Group Task", task: ["Assess a farming community (real or simulated)", "Identify one major agricultural challenge", "Analyze available agricultural resources", "Identify key stakeholders", "Define the agricultural problem clearly"],
        output: "Community Agricultural Assessment Report" },
      wed: { type: "Individual Skill Practice Day", title: "Agribusiness Development, Marketing & Financial Management",
        core: ["Agribusiness Fundamentals", "Agricultural Marketing Strategies", "Value Addition and Agro-Processing", "Farm Record Keeping", "Pricing Agricultural Products", "Cooperative Farming", "Agricultural Financing", "Government Grants and Support Programmes", "Digital Marketing for Agricultural Businesses", "Customer Relations and Business Ethics"],
        taskType: "Individual Task", task: ["Develop a simple agribusiness idea", 'Write: "How I Can Build a Successful Agricultural Business."', "Prepare a one-minute pitch for an agricultural product", "List five qualities of a successful agribusiness entrepreneur"],
        output: "Individual Agribusiness Development Plan" },
      thu: { type: "Group Project Development Day", title: "Sustainable Agriculture, Food Security & Community Development",
        core: ["Food Security and Nutrition", "Sustainable Farming Practices", "Mechanized Agriculture", "Climate Change and Agriculture", "Post-Harvest Handling and Storage", "Agricultural Extension Services", "Community-Based Farming Models", "Agricultural Cooperatives", "Rural Development Strategies", "Project Planning for Agricultural Enterprises"],
        taskType: "Group Task", task: ["Develop a practical agricultural solution to Tuesday’s challenge", "Assign responsibilities among team members", "Prepare an implementation strategy", "Estimate resources and support required"],
        output: "Group Agricultural Development Strategy" },
      fri: { type: "Capstone Project Day", title: "Agricultural Enterprise Development & Community Solutions",
        core: ["Transforming Agricultural Ideas into Sustainable Enterprises", "Agricultural Project Planning", "Farm Business Models", "Budgeting and Cost Estimation", "Agricultural Risk Management", "Monitoring and Evaluation", "Stakeholder Engagement", "Preparing Professional Agricultural Project Presentations"],
        taskType: "Capstone · Group Task", task: ["Problem Definition", "Agricultural Development Strategy", "Implementation Plan", "Team Responsibilities", "Expected Outcomes"],
        output: "Final Capstone Project Document" },
      sat: { type: "Graduation", theme: "Presenting Agricultural Solutions, Celebrating Excellence & Becoming Certified Professionals",
        present: ["Agricultural challenge identified", "Community background", "Root cause analysis", "Proposed solution", "Implementation plan", "Expected outcomes and community impact", "Q&A with the assessment panel"],
        criteria: ["Problem Identification and Analysis", "Practicality of the Proposed Solution", "Innovation and Creativity", "Feasibility and Sustainability", "Team Collaboration", "Communication and Presentation Skills", "Professionalism"],
        awards: ["Best Agricultural Development Project", "Best Agribusiness Innovation", "Most Sustainable Farming Solution", "Best Team Collaboration", "Best Project Presentation", "Outstanding Participant"] },
    },
  },
  entre: {
    icon: "graph-up-arrow",
    name: "Entrepreneurship & Wealth Creation",
    blurb: "Build, fund, and grow a business, from idea validation to scaling.",
    progress: 0, dayLabel: "Starts Monday",
    cert: "Professional Certificate in Entrepreneurship & Wealth Creation",
    days: {
      mon: { type: "Individual Class · Activity Day", title: "Introduction to Entrepreneurship & Wealth Creation",
        core: ["Understanding Entrepreneurship and Wealth Creation", "Characteristics of Successful Entrepreneurs", "Entrepreneurial Mindset and Personal Development", "Identifying Business Opportunities", "Solving Problems Through Innovation", "Employment vs Entrepreneurship", "Types of Business Ownership", "Principles of Wealth Creation", "Financial Discipline and Wealth Management", "Career Opportunities in Entrepreneurship"],
        taskType: "Individual Task", task: ['Write: "What Entrepreneurship Means to Me."', "Identify three business opportunities in your community", "List your entrepreneurial strengths and areas to improve", "Describe one business you would start and why"],
        output: "Personal Entrepreneurship Reflection Sheet" },
      tue: { type: "Group Class · Collaboration Day", title: "Business Opportunity Analysis & Market Validation",
        core: ["Identifying Market Needs", "Conducting Market Research", "Understanding Customer Needs", "Competitor Analysis", "Developing Value Propositions", "Business Idea Validation", "Product and Service Development", "Pricing Strategies", "Customer Segmentation", "Risk Identification in Business"],
        taskType: "Group Task", task: ["Identify a business opportunity in a community", "Analyze the target market and customer needs", "Identify competitors and market gaps", "Define the business problem your venture solves"],
        output: "Business Opportunity Assessment Report" },
      wed: { type: "Individual Skill Practice Day", title: "Business Planning, Financial Management & Marketing",
        core: ["Developing a Business Model", "Writing a Simple Business Plan", "Business Registration Basics", "Financial Planning and Budgeting", "Record Keeping and Cash Flow", "Pricing and Profitability", "Sales and Marketing Strategies", "Branding and Customer Service", "Digital Marketing for Small Businesses", "Business Ethics and Professionalism"],
        taskType: "Individual Task", task: ["Prepare a simple business plan for your idea", 'Write: "How I Plan to Build Sustainable Wealth."', "Develop a one-minute business pitch", "List five strategies for growing a business"],
        output: "Individual Business Development Plan" },
      thu: { type: "Group Project Development Day", title: "Business Growth Strategies & Enterprise Development",
        core: ["Scaling a Business", "Innovation and Business Expansion", "Customer Relationship Management", "Business Risk Management", "Access to Funding and Investment", "Partnerships and Networking", "Leadership in Business", "Business Sustainability", "Social Entrepreneurship", "Monitoring and Evaluating Performance"],
        taskType: "Group Task", task: ["Develop a sustainable business model from Tuesday’s opportunity", "Assign responsibilities among team members", "Prepare a market entry strategy", "Develop an implementation roadmap"],
        output: "Group Business Growth Strategy" },
      fri: { type: "Capstone Project Day", title: "Enterprise Development & Wealth Creation Strategy",
        core: ["Turning Business Ideas into Enterprises", "Business Growth Planning", "Investment Readiness", "Revenue Generation Strategies", "Financial Risk Management", "Wealth Creation Through Entrepreneurship", "Measuring Business Performance", "Preparing Professional Business Presentations"],
        taskType: "Capstone · Group Task", task: ["Business Problem Statement", "Enterprise Development Strategy", "Marketing Plan", "Financial Plan", "Implementation Timeline", "Expected Outcomes"],
        output: "Final Capstone Project Document" },
      sat: { type: "Graduation", theme: "Presenting Business Solutions, Celebrating Innovation & Becoming Certified Entrepreneurs",
        present: ["Business problem identified", "Market opportunity", "Proposed business solution", "Business model", "Marketing and financial strategy", "Implementation plan", "Expected business and community impact", "Q&A with the assessment panel"],
        criteria: ["Problem Identification and Market Relevance", "Innovation and Creativity", "Practicality and Feasibility", "Financial Viability", "Team Collaboration", "Communication and Presentation Skills", "Professionalism"],
        awards: ["Best Business Idea", "Best Business Plan", "Most Innovative Enterprise", "Best Team Collaboration", "Best Project Presentation", "Outstanding Participant"] },
    },
  },
  digital: {
    icon: "cpu",
    name: "Digital Skills",
    blurb: "The skills that pay online: web, design, data, and AI tools for remote work.",
    progress: 0, dayLabel: "Starts Monday",
    cert: "Professional Certificate in Digital Skills",
    days: {
      mon: { type: "Individual Class · Activity Day", title: "Digital Literacy, Emerging Technologies & the Digital Economy",
        core: ["Introduction to Digital Skills and Transformation", "Understanding Computer Systems and Devices", "Internet Fundamentals and Navigation", "Cloud Computing and Storage", "Digital Communication and Collaboration", "Microsoft Office and Google Workspace", "AI and Everyday Applications", "Cybersecurity Awareness and Online Safety", "Digital Ethics and Responsible Use", "Careers in the Digital Economy"],
        taskType: "Individual Task", task: ['Write: "How Digital Skills Can Transform My Life and Career."', "Assess your current digital skill level", "Identify five digital skills you want to acquire", "List three digital problems in your community or workplace"],
        output: "Personal Digital Skills Development Plan" },
      tue: { type: "Group Class · Collaboration Day", title: "Digital Productivity, Collaboration & Technology Solutions",
        core: ["Digital Productivity Tools", "Online Collaboration Platforms", "File Management and Cloud Collaboration", "Online Research Techniques", "Data Collection and Information Management", "Digital Communication Best Practices", "Introduction to Graphic Design Tools", "Website and Mobile App Concepts", "Using AI Tools for Productivity", "Solving Problems with Technology"],
        taskType: "Group Task", task: ["Identify a challenge facing a business, school, or community", "Analyze how technology can solve it", "Assign responsibilities among team members", "Develop a digital solution concept"],
        output: "Digital Problem Analysis and Solution Report" },
      wed: { type: "Individual Skill Practice Day", title: "Digital Marketing, Content Creation & Online Business",
        core: ["Digital Entrepreneurship Fundamentals", "Personal Branding and Professional Presence", "Social Media Management", "Graphic Design for Business", "Content Creation Strategies", "Video and Short-Form Media", "SEO Basics", "E-commerce and Online Business Models", "Freelancing and Remote Work", "Using AI Tools for Business Growth"],
        taskType: "Individual Task", task: ["Create a professional digital profile", "Design a promotional graphic for a business or cause", "Develop a one-minute digital business pitch", 'Write: "How I Plan to Build a Career Using Digital Skills."'],
        output: "Individual Digital Portfolio" },
      thu: { type: "Group Project Development Day", title: "Digital Innovation, Project Development & Technology Leadership",
        core: ["Innovation in the Digital Economy", "Design Thinking for Digital Solutions", "Digital Project Management", "Technology for Small Business Growth", "Digital Transformation Strategies", "Cybersecurity and Data Protection", "Team Collaboration in Tech Projects", "Business Process Automation", "Emerging Technologies and Careers", "Building Sustainable Digital Solutions"],
        taskType: "Group Task", task: ["Design a practical digital solution from Tuesday’s challenge", "Develop an implementation strategy", "Assign project responsibilities", "Prepare a solution presentation"],
        output: "Group Digital Innovation Strategy" },
      fri: { type: "Capstone Project Day", title: "Digital Solution Development & Technology Entrepreneurship",
        core: ["Transforming Ideas into Digital Solutions", "Technology-Based Business Models", "Digital Product Development", "Innovation and Entrepreneurship", "Budgeting and Resource Planning", "Risk Assessment and Mitigation", "Measuring Digital Project Success", "Preparing Professional Presentations"],
        taskType: "Capstone · Group Task", task: ["Problem Statement", "Digital Solution Design", "Implementation Strategy", "Team Roles and Responsibilities", "Expected Outcomes"],
        output: "Final Capstone Project Document" },
      sat: { type: "Graduation", theme: "Showcasing Digital Innovation & Celebrating Future Digital Professionals",
        present: ["Problem identified", "Research findings", "Proposed digital solution", "Technology and tools used", "Implementation strategy", "Expected outcomes and impact", "Live demonstration or prototype", "Q&A with the assessment panel"],
        criteria: ["Innovation and Creativity", "Relevance of the Digital Solution", "Practicality and Feasibility", "Technical Understanding", "Sustainability", "Team Collaboration", "Communication and Presentation Skills", "Professionalism"],
        awards: ["Best Digital Innovation Project", "Best Technology Solution", "Most Innovative Digital Business Idea", "Best Team Collaboration", "Best Project Presentation", "Outstanding Participant"] },
    },
  },
  trade: {
    icon: "box-seam",
    name: "Import & Export Strategies",
    blurb: "Sourcing, logistics, documentation, and trade finance for cross-border business.",
    progress: 0, dayLabel: "Starts Monday",
    cert: "Professional Certificate in Import & Export Strategies",
    days: {
      mon: { type: "Individual Class · Activity Day", title: "Introduction to International Trade & Import-Export Business",
        core: ["Introduction to International Trade", "Understanding Import and Export Business", "Importance of Global Trade to Development", "Traits of Successful Importers and Exporters", "Identifying International Opportunities", "Understanding Global Supply Chains", "Import and Export Terminologies", "Business Ethics in International Trade", "Agencies Regulating International Trade", "Careers in Import and Export"],
        taskType: "Individual Task", task: ['Write: "Why I Want to Start an Import or Export Business."', "Identify five products Nigeria imports", "Identify five products Nigeria can export", "List three international trade opportunities near you"],
        output: "Personal Import & Export Reflection Sheet" },
      tue: { type: "Group Class · Collaboration Day", title: "Product Sourcing, Supplier Identification & Market Analysis",
        core: ["Identifying High-Demand Products", "Product Sourcing Strategies", "Finding Reliable International Suppliers", "Understanding Target Markets", "Market Research Techniques", "Competitor Analysis", "Product Pricing Strategies", "Import Cost Estimation", "Export Market Identification", "Risk Assessment in International Trade"],
        taskType: "Group Task", task: ["Identify an import or export business opportunity", "Analyze market demand", "Identify target customers", "Assess potential suppliers or buyers", "Define the business opportunity clearly"],
        output: "Import & Export Market Assessment Report" },
      wed: { type: "Individual Skill Practice Day", title: "Trade Documentation, Logistics & Customs Procedures",
        core: ["Import Documentation", "Export Documentation", "Bills of Lading", "Commercial Invoices", "Packing Lists", "Certificates of Origin", "Customs Clearance Procedures", "Freight Forwarding", "Shipping Methods (Air, Sea, Land)", "Warehouse and Inventory Management"],
        taskType: "Individual Task", task: ["Prepare a simple import or export process flow", "List key documents required for trade", 'Write: "How Proper Documentation Reduces Business Risks."', "Identify five logistics challenges in trade"],
        output: "Individual Trade Operations Plan" },
      thu: { type: "Group Project Development Day", title: "International Trade Strategy, Risk Management & Growth",
        core: ["Developing an Import & Export Business Model", "International Marketing Strategies", "Trade Financing Options", "Foreign Exchange Basics", "International Payment Methods", "Trade Risk Management", "Customer Relationship Management", "Negotiation Skills in Trade", "Digital Platforms for Global Trade", "Building Sustainable International Businesses"],
        taskType: "Group Task", task: ["Develop a complete import or export strategy", "Assign responsibilities among team members", "Prepare an implementation roadmap", "Develop a market entry strategy"],
        output: "Group Import & Export Business Strategy" },
      fri: { type: "Capstone Project Day", title: "International Trade Business Development & Market Expansion",
        core: ["Building Sustainable Import & Export Businesses", "Global Trade Opportunities", "Business Expansion Strategies", "Budgeting and Cost Analysis", "International Trade Regulations", "Risk Identification and Mitigation", "Business Performance Measurement", "Preparing Professional Trade Presentations"],
        taskType: "Capstone · Group Task", task: ["Business Opportunity Statement", "Import or Export Strategy", "Logistics and Operations Plan", "Team Responsibilities", "Expected Outcomes"],
        output: "Final Capstone Project Document" },
      sat: { type: "Graduation", theme: "Showcasing Global Trade Strategies & Celebrating Future International Business Professionals",
        present: ["Business opportunity identified", "Market research findings", "Product selection", "Import or export strategy", "Logistics and operational plan", "Financial projections", "Expected outcomes and economic impact", "Q&A with the assessment panel"],
        criteria: ["Market Opportunity Analysis", "Innovation and Business Creativity", "Practicality and Feasibility", "Understanding of International Trade", "Financial Viability", "Team Collaboration", "Communication and Presentation Skills"],
        awards: ["Best Import & Export Business Strategy", "Best Market Research Project", "Most Innovative Trade Opportunity", "Best Team Collaboration", "Best Project Presentation", "Outstanding Participant"] },
    },
  },
  eng: {
    icon: "gear-wide-connected",
    name: "Engineering Technology",
    blurb: "Applied engineering fundamentals and hands-on technical problem-solving.",
    progress: 0, dayLabel: "Starts Monday",
    cert: "Professional Certificate in Engineering Technology",
    days: {
      mon: { type: "Individual Class · Activity Day", title: "Introduction to Engineering Technology & Innovation",
        core: ["Introduction to Engineering Technology", "Branches of Engineering (Civil, Mechanical, Electrical, Electronics, Computer, Environmental)", "Engineering Design Process", "Engineering Ethics and Professional Conduct", "Engineering Safety Standards", "Basic Engineering Mathematics and Measurements", "Technical Drawing and Design Concepts", "Emerging Technologies in Engineering", "Innovation and Problem-Solving", "Careers in Engineering Technology"],
        taskType: "Individual Task", task: ['Write: "What Engineering Technology Means to Me."', "Identify three engineering problems in your community", "List five engineering technologies used in daily life", "Describe an engineering innovation that improved society"],
        output: "Personal Engineering Reflection Sheet" },
      tue: { type: "Group Class · Collaboration Day", title: "Engineering Design, Materials & Technical Problem Solving",
        core: ["Engineering Design Thinking", "Identifying Engineering Problems", "Engineering Materials and Applications", "Basic Structural Concepts", "Electrical and Mechanical Systems Overview", "Engineering Drawings and Sketches", "Technology in Infrastructure Development", "Sustainable Engineering Practices", "Technical Risk Assessment", "Team-Based Engineering Design"],
        taskType: "Group Task", task: ["Identify an engineering or infrastructure challenge in a community", "Analyze the causes of the problem", "Brainstorm practical engineering solutions", "Assign team responsibilities"],
        output: "Engineering Problem Analysis Report" },
      wed: { type: "Individual Skill Practice Day", title: "Engineering Project Planning, Technology Management & Maintenance",
        core: ["Engineering Project Planning", "Equipment and Facility Maintenance", "Quality Assurance and Control", "Engineering Project Documentation", "Project Cost Estimation", "Technology Management", "Workplace Safety and Risk Management", "Digital Technologies in Engineering", "Engineering Communication Skills", "Leadership in Engineering Projects"],
        taskType: "Individual Task", task: ["Develop a simple engineering project proposal", 'Write: "How Engineering Can Improve My Community."', "Prepare a maintenance plan for a system or facility", "List five qualities of an effective engineering technologist"],
        output: "Individual Engineering Project Plan" },
      thu: { type: "Group Project Development Day", title: "Engineering Innovation, Smart Technologies & Infrastructure",
        core: ["Engineering Innovation and Creativity", "Smart Infrastructure and Sustainable Development", "Renewable Energy Technologies", "Automation and Industrial Technology", "Digital Engineering Tools", "Environmental Engineering Principles", "Project Implementation Strategies", "Team Collaboration in Engineering", "Monitoring Engineering Projects", "Preparing Technical Presentations"],
        taskType: "Group Task", task: ["Design a practical engineering solution from Tuesday’s challenge", "Develop an implementation strategy", "Assign project responsibilities", "Prepare a technical presentation"],
        output: "Group Engineering Development Strategy" },
      fri: { type: "Capstone Project Day", title: "Engineering Solution Development & Technology Innovation",
        core: ["Transforming Engineering Ideas into Solutions", "Engineering Project Development", "Technology Commercialization", "Budgeting and Resource Planning", "Engineering Risk Assessment", "Project Monitoring and Evaluation", "Sustainable Engineering Solutions", "Preparing Professional Presentations"],
        taskType: "Capstone · Group Task", task: ["Engineering Problem Statement", "Solution Design", "Implementation Strategy", "Team Roles and Responsibilities", "Expected Outcomes"],
        output: "Final Capstone Project Document" },
      sat: { type: "Graduation", theme: "Showcasing Engineering Innovation & Celebrating Future Technology Professionals",
        present: ["Engineering problem identified", "Background and technical analysis", "Proposed engineering solution", "Technical design and implementation strategy", "Materials and technologies required", "Expected outcomes and community impact", "Q&A with the assessment panel"],
        criteria: ["Problem Analysis", "Innovation and Creativity", "Technical Feasibility", "Practicality and Sustainability", "Quality of Engineering Design", "Team Collaboration", "Communication and Presentation Skills"],
        awards: ["Best Engineering Innovation Project", "Best Technical Solution", "Most Innovative Engineering Design", "Best Team Collaboration", "Best Project Presentation", "Outstanding Participant"] },
    },
  },
};